import { Bus, Car, CarFront, Crown, Gauge, Gem, Leaf, Mountain, Package, Truck, Wind, Zap, Icon } from "lucide-react";

export const vehicleCalssIcons: any = {
  "city_car": Car,
  "economy": Car,
  "compact": Car,
  "midsize": CarFront,
  "standard": CarFront,
  "full_size": CarFront,
  "crossover": CarFront,
  "suv_compact": CarFront,
  "suv_midsize": CarFront,
  "suv_full_size": CarFront,
  "sedan": Car,
  "hatchback": Car,
  "wagon_estate": Car,
  "coupe": Car,
  "convertible_cabrio": Wind,
  "pickup": Truck,
  "minivan_mpv": Bus,
  "passenger_van": Bus,
  "cargo_van": Package,
  "offroad_4x4": Mountain,
  "sports_performance": Gauge,
  "premium": Crown,
  "luxury": Gem,
  "electric_bev": Zap,
  "hybrid_phev": Leaf,
}